version: '3'

services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: proxy-manager
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./nginx/nginxdata:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - monitoring_netwerk

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - monitoring_netwerk
    volumes:
      - ./grafana:/var/lib/grafana
    user: "0:0"

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: unless-stopped
    ports:
      - '8080:80'
      - '2003-2004:2003-2004'
      - '2023-2024:2023-2024'
      - '8125:8125/udp'
      - '8126:8126'
    networks:
      - monitoring_netwerk
    volumes:
      - ./graphite/config:/opt/graphite/conf
      - ./graphite/whisper:/opt/graphite/storage
    environment:
      - GRAPHITE_TIME_ZONE=Europe/Amsterdam

networks:
  monitoring_netwerk:
